name: CI setup

runs:
  using: composite
  steps:
    - name: Setup Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Grand execute permissions to gradlew
      run: chmod +x gradlew
      shell: bash