ktor:
  deployment:
    port: 8081
  application:
    modules:
      - io.github.taetae98coding.diary.ApplicationKt.module

database:
  url: $DIARY_DATABASE_URL
  user: $DIARY_DATABASE_USER
  password: $DIARY_DATABASE_PASSWORD

firebase:
  key: $DIARY_FIREBASE_ADMIN_KEY