name: Run Build

on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Set up JDK
        uses: actions/setup-java@main
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up gradle permission
        run: chmod +x gradlew

      - name: Cache Gradle
        uses: actions/cache@main
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set LocalProperties
        run:
          echo "google.debug.server.client.id=$GOOGLE_SERVER_CLIENT_ID
          
          buildkonfig.flavor=debug
          
          key.debug.store.password=$ANDROID_DEBUG_KEY_PASSWORD
          
          key.debug.password=$ANDROID_DEBUG_KEY_ALIAS_PASSWORD
          
          key.debug.alias=$ANDROID_DEBUG_KEY_ALIAS
          
          key.release.store.password=$ANDROID_RELEASE_KEY_PASSWORD

          key.release.password=$ANDROID_RELEASE_KEY_ALIAS_PASSWORD

          key.release.alias=$ANDROID_RELEASE_KEY_ALIAS
          
          google.release.server.client.id=$GOOGLE_RELEASE_SERVER_CLIENT_ID
          
          google.release.ios.client.id=$GOOGLE_RELEASE_IOS_CLIENT_ID
          
          google.debug.server.client.id=$GOOGLE_DEBUG_SERVER_CLIENT_ID
          
          google.debug.ios.client.id=GOOGLE_DEBUG_IOS_CLIENT_ID" > ./local.properties
        shell: bash
        env:
          ANDROID_DEBUG_KEY_PASSWORD: ${{ secrets.ANDROID_DEBUG_KEY_PASSWORD }}
          ANDROID_DEBUG_KEY_ALIAS: ${{ secrets.ANDROID_DEBUG_KEY_ALIAS }}
          ANDROID_DEBUG_KEY_ALIAS_PASSWORD: ${{ secrets.ANDROID_DEBUG_KEY_ALIAS_PASSWORD }}
          ANDROID_RELEASE_KEY_PASSWORD: ${{ secrets.ANDROID_RELEASE_KEY_PASSWORD }}
          ANDROID_RELEASE_KEY_ALIAS: ${{ secrets.ANDROID_RELEASE_KEY_ALIAS }}
          ANDROID_RELEASE_KEY_ALIAS_PASSWORD: ${{ secrets.ANDROID_RELEASE_KEY_ALIAS_PASSWORD }}
          GOOGLE_DEBUG_SERVER_CLIENT_ID: ${{ secrets.GOOGLE_DEBUG_SERVER_CLIENT_ID }}
          GOOGLE_DEBUG_IOS_CLIENT_ID: ${{ secrets.GOOGLE_DEBUG_IOS_CLIENT_ID }}
          GOOGLE_RELEASE_SERVER_CLIENT_ID: ${{ secrets.GOOGLE_RELEASE_SERVER_CLIENT_ID }}
          GOOGLE_RELEASE_IOS_CLIENT_ID: ${{ secrets.GOOGLE_RELEASE_IOS_CLIENT_ID }}
          OPEN_API_DEBUG_HOLIDAY_URL: ${{ secrets.OPEN_API_DEBUG_HOLIDAY_URL }}
          OPEN_API_DEBUG_HOLIDAY_KEY: ${{ secrets.OPEN_API_DEBUG_HOLIDAY_KEY }}
          OPEN_API_RELEASE_HOLIDAY_URL: ${{ secrets.OPEN_API_RELEASE_HOLIDAY_URL }}
          OPEN_API_RELEASE_HOLIDAY_KEY: ${{ secrets.OPEN_API_RELEASE_HOLIDAY_KEY }}

      - name: Set Android Debug GoogleServiceJson
        run:
          echo "$GOOGLE_DEBUG_SERVICE_JSON" > ./target/androidApp/src/debug/google-services.json
          
          echo "$GOOGLE_RELEASE_SERVICE_JSON" > ./target/androidApp/src/release/google-services.json
        shell: bash
        env:
          GOOGLE_DEBUG_SERVICE_JSON: ${{ secrets.ANDROID_DEBUG_GOOGLE_SERVICE_JSON }}
          GOOGLE_RELEASE_SERVICE_JSON: ${{ secrets.ANDROID_RELEASE_GOOGLE_SERVICE_JSON }}

      - name: Set iOS Debug GoogleServicePlist
        run:
          echo "$GOOGLE_DEBUG_SERVICE_PLIST" > ./xcode/Diary/GoogleService/debug/GoogleService-Info.plist
          
          echo "$GOOGLE_RELEASE_SERVICE_PLIST" > ./xcode/Diary/GoogleService/release/GoogleService-Info.plist
        shell: bash
        env:
          GOOGLE_DEBUG_SERVICE_PLIST: ${{ secrets.IOS_DEBUG_GOOGLE_SERVICE_PLIST }}
          GOOGLE_RELEASE_SERVICE_PLIST: ${{ secrets.IOS_RELEASE_GOOGLE_SERVICE_PLIST }}
      - name: Build Gradle
        uses: gradle/gradle-build-action@main
        with:
          arguments: build